remote_theme: "mmistakes/so-simple-theme@3.2.0"
title : "Données et médiation"
description : "Production des étudiantes et étudiants du master Métiers de l'Information à Sciences Po Aix"
logo : "https://upload.wikimedia.org/wikipedia/fr/thumb/3/3f/Institut_d%27%C3%A9tudes_politiques_d%27Aix-en-Provence_%28logo_2009%29.svg/320px-Institut_d%27%C3%A9tudes_politiques_d%27Aix-en-Provence_%28logo_2009%29.svg.png"
